### ISSUE TITLE
multi Unpivot

### ISSUE THREAD

**Issue by Gurupra** [unislink/dataextractor#10]
1. Multiple Mapping is not working as expected. Only the first one is taken into consideration and others are getting skipped.
2. In Unpivot, type and data values are getting swapped if you rum multiple times i.e. pivotvalueColumns are not getting mapped properly.

**Comment by thangarajan8** [comment]
Now Type and Data values not swapped
`selectedColumns[pos:pos+1] = set(pivotvalueColumn)` to `selectedColumns[pos:pos+1] = pivotvalueColumn`

**Comment by Gurupra** [comment]
Fixed
