### ISSUE TITLE
multi unpivot - Integer conversion issue

### ISSUE THREAD

**Issue by Gurupra** [unislink/dataextractor#15]

**Comment by thangarajan8** [comment]
what was the error you are getting. please give some sample output.

**Comment by Gurupra** [comment]
value in input file: 86549
value in output file: 86549.0

**Comment by thangarajan8** [comment]
Issue fixed by adding `dtype = str` argument in `read_csv` and `read_csv_as_chunk` . Please check and update the same.

**Comment by Gurupra** [comment]
Working good.
