### ISSUE TITLE
queryToFile - Parallel Access Issue

### ISSUE THREAD

**Issue by Gurupra** [unislink/dataextractor#4]
Traceback (most recent call last):
  File "queryToFile.py", line 59, in <module>
    com.zip_files(zip_file_location, output_file_names)
  File "utils\common.py", line 446, in zip_files
    os.remove(file)
PermissionError: [WinError 5] Access is denied: 'tests\\queryToFile\\Output'

**Comment by thangarajan8** [comment]
Fixed please check and confirm

**Comment by Gurupra** [comment]
Fixed
