### ISSUE TITLE
queryToFile - Zip Issue

### ISSUE THREAD

**Issue by Gurupra** [unislink/dataextractor#6]
Zip logic is not working as expected. 

1. Lets zip at file level instead of folder level
2. We can place the zip file in the Output path being passed instead of current logic where file would be placed at parent level to the output path being passed
3. Once we zip the files, lets remove the respective files

**Comment by thangarajan8** [comment]
1. Now zip file created in file level by adding change directory.
2. Fixed
3. Fixed

Please check and confirm me

**Comment by Gurupra** [comment]
Tested and working as expected
