### ISSUE TITLE
queryToFile - MySQL connectivity issue

### ISSUE THREAD

**Issue by Gurupra** [unislink/dataextractor#7]
1. MYSql connection cannot be established
2. In case of mysql, we would be using ## instead of --
3. Use the same zip logic mentioned earlier

**Comment by thangarajan8** [comment]
Fixed MySQL Connection issue

**Comment by thangarajan8** [comment]
## fixed for MySQL connection

**Comment by thangarajan8** [comment]
Fixed please Check and Confirm

**Comment by Gurupra** [comment]
Tested and working good.
